name: Build Release Binaries

on:
  release:
    types: [created]

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64, mips, mips64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: "mips"
            goos: darwin
          - goarch: "mips64"
            goos: darwin
          - goarch: "mips"
            goos: windows
          - goarch: "mips64"
            goos: windows
#           - goarch: arm64
#             goos: windows
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1.35
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://dl.google.com/go/go1.19.5.linux-amd64.tar.gz"
#         project_path: "./cmd/test-binary"
        binary_name: "podgen"
        extra_files: LICENSE README.md
